FROM debian:testing-slim
RUN apt-get update && apt-get install -y --no-install-recommends rsyslog curl && rm -rf /var/lib/apt/lists/*
COPY rsyslog/syslog.conf /etc/rsyslog.d/syslog.conf
EXPOSE 514 514/udp
CMD ["rsyslogd", "-n"]