FROM node:20-alpine AS builder
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
WORKDIR /app
COPY frontend/package.json frontend/.npmrc ./
RUN npm config set ca "" && npm install --no-audit --no-fund
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80