package handler

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"database/sql"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"syslytics/audit"
	"syslytics/db"
	"syslytics/middleware"
	"syslytics/model"
	"syslytics/relaypki"

	"github.com/gin-gonic/gin"
)

// relayPKIDir is where the CA, the central listener's server cert, and the
// generated ACL live - a subdirectory of the same shared volume the api and
// rsyslog containers already both mount at /data (see docker-compose.yml).
func relayPKIDir() string {
	if v := os.Getenv("RELAY_PKI_DIR"); v != "" {
		return v
	}
	return "/data/relay"
}

func relayACLPath() string {
	return filepath.Join(relayPKIDir(), "allowed-relays.conf")
}

// writeRelayACL regenerates the rsyslog snippet that gates the mTLS relay
// listener (ruleset "relayIngest" in rsyslog/syslog.conf, which includes
// this file): a valid client certificate alone is not enough to get in, the
// peer's IP must also be on the current whitelist. When the feature is
// disabled or no relay is whitelisted yet, every connection is dropped.
func writeRelayACL(database *sql.DB) error {
	enabled := db.GetSetting(database, "relay_ingestion_enabled", "false") == "true"

	var content string
	if !enabled {
		content = "# Relay ingestion is disabled (Admin > Settings) - dropping all connections.\nstop\n"
	} else {
		entries, err := db.GetRelayWhitelist(database)
		if err != nil {
			return fmt.Errorf("load relay whitelist: %w", err)
		}
		if len(entries) == 0 {
			content = "# Relay ingestion is enabled but no relay IPs are whitelisted yet - dropping all connections.\nstop\n"
		} else {
			var b strings.Builder
			b.WriteString("# Auto-generated by the API (Admin > Syslog Relay) - do not edit manually.\n")
			b.WriteString("if ")
			for i, e := range entries {
				if i > 0 {
					b.WriteString(" or ")
				}
				fmt.Fprintf(&b, "$fromhost-ip == %q", e.IPAddress)
			}
			b.WriteString(" then {\n    call relayAccept\n} else {\n    stop\n}\n")
			content = b.String()
		}
	}

	dir := relayPKIDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create relay pki dir: %w", err)
	}
	tmpPath := relayACLPath() + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write relay acl: %w", err)
	}
	return os.Rename(tmpPath, relayACLPath())
}

// reloadRelayConfig asks the rsyslog container's reload sidecar (same
// pattern as the frontend's nginx reload sidecar, see postReload in
// admin.go) to HUP rsyslogd so the regenerated ACL takes effect without a
// container restart. RSYSLOG_RELOAD_TARGETS_HOST mirrors
// NGINX_RELOAD_TARGETS_HOST: unset for the single-server/single-rsyslog
// case (docker-compose.yml), set to a DNS name resolving to every edge
// node's task IP (e.g. Swarm's "tasks.rsyslog") when rsyslog runs
// `mode: global` across multiple edge nodes (docker-stack.app.yml) - every
// node needs its ACL reloaded, not just whichever one currently holds the
// keepalived VIP.
func reloadRelayConfig() error {
	targetsHost := os.Getenv("RSYSLOG_RELOAD_TARGETS_HOST")
	if targetsHost == "" {
		url := os.Getenv("RSYSLOG_RELOAD_URL")
		if url == "" {
			url = "http://rsyslog:8082/cgi-bin/reload.sh"
		}
		return postReload(url)
	}

	port := os.Getenv("RSYSLOG_RELOAD_PORT")
	if port == "" {
		port = "8082"
	}

	ips, err := net.LookupHost(targetsHost)
	if err != nil {
		return fmt.Errorf("resolve rsyslog reload targets %q: %w", targetsHost, err)
	}
	if len(ips) == 0 {
		return fmt.Errorf("rsyslog reload targets %q resolved to no addresses", targetsHost)
	}

	type reloadResult struct {
		ip  string
		err error
	}
	results := make(chan reloadResult, len(ips))
	for _, ip := range ips {
		go func(ip string) {
			url := fmt.Sprintf("http://%s:%s/cgi-bin/reload.sh", ip, port)
			results <- reloadResult{ip: ip, err: postReload(url)}
		}(ip)
	}

	succeeded := 0
	var failures []string
	for i := 0; i < len(ips); i++ {
		r := <-results
		if r.err != nil {
			failures = append(failures, fmt.Sprintf("%s: %v", r.ip, r.err))
			continue
		}
		succeeded++
	}

	if succeeded == 0 {
		return fmt.Errorf("rsyslog reload failed on all %d target(s): %s", len(ips), strings.Join(failures, "; "))
	}
	if len(failures) > 0 {
		slog.Warn("rsyslog relay reload failed on some targets", "succeeded", succeeded, "total", len(ips), "errors", strings.Join(failures, "; "))
	}
	return nil
}

// SyncRelayConfig ensures the shared /data/relay PKI material exists,
// regenerates the IP allowlist from the current relay_ingestion_enabled
// setting and relay_whitelist table, and reloads rsyslog. Call whenever
// relay settings might have changed, and once at startup (see main.go) so a
// restart re-applies state that lives only in the non-git-tracked shared
// volume.
func SyncRelayConfig(database *sql.DB) error {
	if err := relaypki.EnsureCA(relayPKIDir()); err != nil {
		return fmt.Errorf("ensure relay CA: %w", err)
	}
	if err := writeRelayACL(database); err != nil {
		return err
	}
	return reloadRelayConfig()
}

// SyncRelayConfigWithRetry retries SyncRelayConfig a few times with a fixed
// delay, smoothing over the brief window where the rsyslog container's
// reload sidecar isn't listening yet (startup race, same as
// reloadNginxWithRetry).
func SyncRelayConfigWithRetry(database *sql.DB, attempts int, delay time.Duration) error {
	var err error
	for i := 0; i < attempts; i++ {
		if err = SyncRelayConfig(database); err == nil {
			return nil
		}
		if i < attempts-1 {
			time.Sleep(delay)
		}
	}
	return err
}

func ListRelayWhitelist(database *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		entries, err := db.GetRelayWhitelist(database)
		if err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to list relay whitelist", err))
			return
		}
		c.JSON(http.StatusOK, entries)
	}
}

func CreateRelayWhitelistEntry(database *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req model.RelayWhitelistRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			middleware.HandleError(c, model.NewBadRequest("Invalid request body", err))
			return
		}

		actorID, actorName := actorFromContext(c)
		entry, err := db.AddRelayWhitelistEntry(database, req.IPAddress, req.Label, nil, actorID)
		if err != nil {
			middleware.HandleError(c, model.NewBadRequest("Failed to add whitelist entry (IP may already be listed)", err))
			return
		}

		audit.LogAudit(database, actorID, actorName, "relay_whitelist_added", c.ClientIP(), fmt.Sprintf("ip=%s label=%s", req.IPAddress, req.Label))

		if err := SyncRelayConfig(database); err != nil {
			slog.Warn("relay config sync failed after whitelist add", "error", err)
			c.JSON(http.StatusCreated, gin.H{"entry": entry, "reload_error": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, entry)
	}
}

func DeleteRelayWhitelistEntry(database *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := parseIDParam(c.Param("id"))
		if err != nil {
			middleware.HandleError(c, model.NewBadRequest("invalid id", nil))
			return
		}
		if err := db.DeleteRelayWhitelistEntry(database, id); err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to delete whitelist entry", err))
			return
		}

		actorID, actorName := actorFromContext(c)
		audit.LogAudit(database, actorID, actorName, "relay_whitelist_removed", c.ClientIP(), fmt.Sprintf("id=%d", id))

		if err := SyncRelayConfig(database); err != nil {
			slog.Warn("relay config sync failed after whitelist delete", "error", err)
			c.JSON(http.StatusOK, gin.H{"message": "whitelist entry deleted", "reload_error": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"message": "whitelist entry deleted"})
	}
}

func ListRelayCertificates(database *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		certs, err := db.GetRelayCertificates(database)
		if err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to list relay certificates", err))
			return
		}
		c.JSON(http.StatusOK, certs)
	}
}

// CreateRelayCertificate issues a new relay client certificate and, in the
// same step, whitelists its IP - then streams the only copy of the private
// key the admin will ever get, as a .tar.gz bundle (ca.crt, client.crt,
// client.key, relay.conf). Nothing here is persisted server-side beyond the
// cert's public metadata (db.InsertRelayCertificate never sees the key).
func CreateRelayCertificate(database *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req model.RelayCertificateRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			middleware.HandleError(c, model.NewBadRequest("Invalid request body", err))
			return
		}

		if err := relaypki.EnsureCA(relayPKIDir()); err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to prepare relay CA", err))
			return
		}

		issued, err := relaypki.IssueClientCert(relayPKIDir(), req.Label)
		if err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to issue relay certificate", err))
			return
		}

		actorID, actorName := actorFromContext(c)

		certID, err := db.InsertRelayCertificate(database, req.Label, issued.SerialHex, issued.Fingerprint, actorID)
		if err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to record relay certificate", err))
			return
		}

		if _, err := db.AddRelayWhitelistEntry(database, req.IPAddress, req.Label, &certID, actorID); err != nil {
			middleware.HandleError(c, model.NewBadRequest("Failed to whitelist relay IP (it may already be listed)", err))
			return
		}

		audit.LogAudit(database, actorID, actorName, "relay_certificate_issued", c.ClientIP(),
			fmt.Sprintf("label=%s ip=%s serial=%s", req.Label, req.IPAddress, issued.SerialHex))

		if err := SyncRelayConfig(database); err != nil {
			// The cert and whitelist entry are already committed - surfacing
			// this as a hard failure would make the admin think issuance
			// failed and retry, ending up with two certs for one relay. Log
			// it; the next successful sync (e.g. the next whitelist/cert
			// change, or the startup retry loop) picks up this state anyway.
			slog.Warn("relay config sync failed after certificate issue", "error", err)
		}

		bundle, err := buildRelayBundle(issued, req.Label)
		if err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to build certificate bundle", err))
			return
		}

		filename := fmt.Sprintf("syslog-relay-%s.tar.gz", sanitizeFilename(req.Label))
		c.Header("Content-Disposition", `attachment; filename="`+filename+`"`)
		c.Data(http.StatusOK, "application/gzip", bundle)
	}
}

func RevokeRelayCertificate(database *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := parseIDParam(c.Param("id"))
		if err != nil {
			middleware.HandleError(c, model.NewBadRequest("invalid id", nil))
			return
		}

		if err := db.DeleteRelayWhitelistByCertID(database, id); err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to revoke relay certificate", err))
			return
		}
		if err := db.RevokeRelayCertificate(database, id); err != nil {
			middleware.HandleError(c, model.NewInternal("Failed to revoke relay certificate", err))
			return
		}

		actorID, actorName := actorFromContext(c)
		audit.LogAudit(database, actorID, actorName, "relay_certificate_revoked", c.ClientIP(), fmt.Sprintf("id=%d", id))

		if err := SyncRelayConfig(database); err != nil {
			slog.Warn("relay config sync failed after certificate revoke", "error", err)
			c.JSON(http.StatusOK, gin.H{"message": "certificate revoked", "reload_error": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"message": "certificate revoked"})
	}
}

func buildRelayBundle(issued *relaypki.IssuedCert, label string) ([]byte, error) {
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)

	files := []struct {
		name string
		data []byte
	}{
		{"ca.crt", issued.CAPEM},
		{"client.crt", issued.CertPEM},
		{"client.key", issued.KeyPEM},
		{"relay.conf", relayConfSnippet(label)},
	}
	for _, f := range files {
		hdr := &tar.Header{Name: f.name, Mode: 0600, Size: int64(len(f.data))}
		if err := tw.WriteHeader(hdr); err != nil {
			return nil, fmt.Errorf("tar header %s: %w", f.name, err)
		}
		if _, err := tw.Write(f.data); err != nil {
			return nil, fmt.Errorf("tar write %s: %w", f.name, err)
		}
	}
	if err := tw.Close(); err != nil {
		return nil, err
	}
	if err := gz.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// relayConfSnippet is a ready-to-use rsyslog config for the relay side:
// listens on 514/tcp+udp like the standalone single-server rsyslog
// (rsyslog/syslog.conf), but forwards over mTLS instead of writing a local
// file. RELAY_CENTRAL_HOST should be set to this server's address reachable
// from the relay's VLAN; when unset, a placeholder is left for the admin to
// fill in.
func relayConfSnippet(label string) []byte {
	host := os.Getenv("RELAY_CENTRAL_HOST")
	if host == "" {
		host = "<CENTRAL_HOST>"
	}

	tpl := `# Generated for relay %q. Place ca.crt / client.crt / client.key from this
# bundle at /etc/syslog-relay/tls/ on the relay host, then use this file as
# rsyslog.d/relay.conf there. See README "Syslog Relay" for the full
# deployment steps (docker-compose.relay.yml).
module(load="imtcp")
input(type="imtcp" port="514")
module(load="imudp")
input(type="imudp" port="514")

template(name="JsonLines" type="list") {
  constant(value="{")
  constant(value="\"timestamp\":\"")
  property(name="timereported" dateFormat="rfc3339" format="json")
  constant(value="\",\"hostname\":\"")
  property(name="hostname" format="json")
  constant(value="\",\"fromhost_ip\":\"")
  property(name="fromhost-ip" format="json")
  constant(value="\",\"severity\":\"")
  property(name="syslogseverity-text" format="json")
  constant(value="\",\"facility\":\"")
  property(name="syslogfacility-text" format="json")
  constant(value="\",\"app_name\":\"")
  property(name="programname" format="json")
  constant(value="\",\"process_id\":\"")
  property(name="procid" format="json")
  constant(value="\",\"message\":\"")
  property(name="msg" format="json")
  constant(value="\"}\n")
}

*.* action(type="omfwd"
  target=%q port="6514" protocol="tcp"
  template="JsonLines"
  StreamDriver="gtls"
  StreamDriverMode="1"
  StreamDriverAuthMode="x509/certvalid"
  StreamDriverCAFile="/etc/syslog-relay/tls/ca.crt"
  StreamDriverCertFile="/etc/syslog-relay/tls/client.crt"
  StreamDriverKeyFile="/etc/syslog-relay/tls/client.key"
  queue.type="LinkedList"
  queue.filename="relayqueue"
  queue.saveOnShutdown="on"
  queue.maxDiskSpace="1g"
  action.resumeRetryCount="-1"
  action.resumeInterval="10"
)
`
	return []byte(fmt.Sprintf(tpl, label, host))
}

var filenameUnsafeRe = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)

func sanitizeFilename(s string) string {
	s = filenameUnsafeRe.ReplaceAllString(s, "-")
	if s == "" {
		return "relay"
	}
	return s
}
