package parsers

var LinuxParsers = []ParserSeed{
	{
		Name:        "SSHD Auth",
		Description: "Matches successful SSH authentication",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "sshd",
		Regex:       `Accepted\s+(\w+)\s+for\s+(\S+)\s+from\s+(\d+\.\d+\.\d+\.\d+)\s+port\s+(\d+)`,
		Fields: []FieldSeed{
			{Name: "auth_method", Label: "Auth Method", Type: "string"},
			{Name: "username", Label: "Username", Type: "string"},
			{Name: "src_ip", Label: "Source IP", Type: "string"},
			{Name: "src_port", Label: "Source Port", Type: "string"},
		},
	},
	{
		Name:        "SSHD Failed Auth",
		Description: "Matches failed SSH authentication attempts",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "sshd",
		Regex:       `Failed\s+(\w+)\s+for\s+(invalid user\s+)?(\S+)\s+from\s+(\d+\.\d+\.\d+\.\d+)\s+port\s+(\d+)`,
		Fields: []FieldSeed{
			{Name: "auth_type", Label: "Auth Type", Type: "string"},
			{Name: "username", Label: "Username", Type: "string"},
			{Name: "src_ip", Label: "Source IP", Type: "string"},
			{Name: "src_port", Label: "Source Port", Type: "string"},
		},
	},
	{
		Name:        "Systemd Service",
		Description: "Matches systemd service start/stop events",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "systemd",
		Regex:       `(Starting|Started|Stopping|Stopped|Finished|Deactivating|Deactivated|Activating|Activated|Collected)\s+(.+?)(?:\s+[-—].+)?`,
		Fields: []FieldSeed{
			{Name: "action", Label: "Action", Type: "string"},
			{Name: "service", Label: "Service Name", Type: "string"},
		},
	},
	{
		Name:        "Kernel Network",
		Description: "Matches kernel network interface events",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "kernel",
		Regex:       `(\S+):\s+link\s+beacon\s+(\S+)\s+speed\s+(\d+)\s+Mbps`,
		Fields: []FieldSeed{
			{Name: "interface", Label: "Interface", Type: "string"},
			{Name: "status", Label: "Status", Type: "string"},
			{Name: "speed", Label: "Speed Mbps", Type: "string"},
		},
	},
	{
		Name:        "Sudo Command",
		Description: "Matches sudo command execution",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "sudo",
		Regex:       `(\S+)[\[:\s]+COMMAND\s+=\s*(\S+)\s+;?\s*TTY=(\S+)\s+PWD=(\S+)\s+USER=(\S+)`,
		Fields: []FieldSeed{
			{Name: "username", Label: "Username", Type: "string"},
			{Name: "command", Label: "Command", Type: "string"},
			{Name: "tty", Label: "TTY", Type: "string"},
			{Name: "pwd", Label: "Working Dir", Type: "string"},
			{Name: "run_as", Label: "Run As", Type: "string"},
		},
	},
	{
		Name:        "Cron Job",
		Description: "Matches cron job execution",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "CRON",
		Regex:       `\[(\S+)\]\s+(\S+)(?:\s+\((\S+)\))?\s+(\S+)`,
		Fields: []FieldSeed{
			{Name: "job_id", Label: "Job ID", Type: "string"},
			{Name: "action", Label: "Action", Type: "string"},
			{Name: "user", Label: "User", Type: "string"},
			{Name: "command", Label: "Command", Type: "string"},
		},
	},
	{
		Name:        "NetworkManager",
		Description: "Matches NetworkManager device state changes",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "NetworkManager",
		Regex:       `device\s+(\S+)\s+(\S+)\s+(:\s+.+)?`,
		Fields: []FieldSeed{
			{Name: "device", Label: "Device", Type: "string"},
			{Name: "state", Label: "State", Type: "string"},
			{Name: "details", Label: "Details", Type: "string"},
		},
	},
	{
		Name:        "DHCP Client",
		Description: "Matches dhclient lease events",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "dhclient",
		Regex:       `DHCP(\s+\S+)*\s+(\S+)\s+of\s+(\d+\.\d+\.\d+\.\d+)\s+on\s+(\S+)/`,
		Fields: []FieldSeed{
			{Name: "action", Label: "Action", Type: "string"},
			{Name: "ip_address", Label: "IP Address", Type: "string"},
			{Name: "interface", Label: "Interface", Type: "string"},
		},
	},
	{
		Name:        "Firewall Drop",
		Description: "Matches kernel firewall drop/reject messages",
		DeviceType:  "linux",
		MatchType:   "app_name",
		MatchValue:  "kernel",
		Regex:       `(\S+)\s+IN=(\S+)\s+OUT=(\S*)\s+SRC=(\d+\.\d+\.\d+\.\d+)\s+DST=(\d+\.\d+\.\d+\.\d+)`,
		Fields: []FieldSeed{
			{Name: "action", Label: "Action", Type: "string"},
			{Name: "in_iface", Label: "In Interface", Type: "string"},
			{Name: "out_iface", Label: "Out Interface", Type: "string"},
			{Name: "src_ip", Label: "Source IP", Type: "string"},
			{Name: "dst_ip", Label: "Dest IP", Type: "string"},
		},
	},
}