package parsers

func init() {
	AllParsers = append(AllParsers, []ParserSeed{
		{
			Name:        "Ubiquiti AP Event",
			Description: "Matches Ubiquiti UniFi AP connect/disconnect/reboot events",
			DeviceType:  "ubiquiti",
			MatchType:   "hostname",
			MatchValue:  "ubnt*",
			Regex:       `AP\s+([0-9A-Fa-f:]+)\s+(\S+)\s+on\s+(\S+)`,
			Fields: []FieldSeed{
				{Name: "mac_address", Label: "MAC Address", Type: "string"},
				{Name: "event_type", Label: "Event Type", Type: "string"},
				{Name: "site", Label: "Site", Type: "string"},
			},
		},
		{
			Name:        "Ubiquiti Client Connect",
			Description: "Matches Ubiquiti client association events",
			DeviceType:  "ubiquiti",
			MatchType:   "hostname",
			MatchValue:  "ubnt*",
			Regex:       `client\s+([0-9A-Fa-f:]+)\s+(\S+)\s+on\s+(\S+)\s+channel\s+(\d+)$`,
			Fields: []FieldSeed{
				{Name: "client_mac", Label: "Client MAC", Type: "string"},
				{Name: "action", Label: "Action", Type: "string"},
				{Name: "ssid", Label: "SSID", Type: "string"},
				{Name: "channel", Label: "Channel", Type: "string"},
			},
		},
		{
			Name:        "Ubiquiti Firewall Log",
			Description: "Matches Ubiquiti EdgeRouter/Dream Machine iptables-style firewall logs",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "DESCR=",
			Regex:       `\[(\S+)\]\s+DESCR="([^"]+)"\s+IN=(\S*)\s+OUT=(\S*)\s+MAC=(\S*)\s+SRC=(\d+\.\d+\.\d+\.\d+)\s+DST=(\d+\.\d+\.\d+\.\d+)\s+.*?LEN=(\d+)\s+.*?PROTO=(\S+)(?:\s+SPT=(\d+))?(?:\s+DPT=(\d+))?`,
			Fields: []FieldSeed{
				{Name: "rule_id", Label: "Rule ID", Type: "string"},
				{Name: "description", Label: "Description", Type: "string"},
				{Name: "in_iface", Label: "In Interface", Type: "string"},
				{Name: "out_iface", Label: "Out Interface", Type: "string"},
				{Name: "mac_address", Label: "MAC Address", Type: "string"},
				{Name: "src_ip", Label: "Source IP", Type: "string"},
				{Name: "dst_ip", Label: "Dest IP", Type: "string"},
				{Name: "packet_len", Label: "Packet Length", Type: "string"},
				{Name: "proto", Label: "Protocol", Type: "string"},
				{Name: "src_port", Label: "Source Port", Type: "string"},
				{Name: "dst_port", Label: "Dest Port", Type: "string"},
			},
		},
		{
			Name:        "UniFi Network WiFi Client Connected",
			Description: "Matches UniFi Network controller CEF events for WiFi client association (signature 400)",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "|400|WiFi Client Connected|",
			Regex:       `^0\|Ubiquiti\|UniFi Network\|[^|]*\|400\|WiFi Client Connected\|\d+\|UNIFIcategory=(.*?) UNIFIhost=(.*?) UNIFIconnectedToDeviceName=(.*?) UNIFIconnectedToDeviceIp=(\S+) UNIFIconnectedToDeviceMac=(\S+) UNIFIconnectedToDeviceModel=(\S+) UNIFIconnectedToDeviceVersion=(\S+) UNIFIclientAlias=(.*?) UNIFIclientHostname=(\S+) UNIFIclientIp=(\S+) UNIFIclientMac=(\S+) UNIFIwifiChannel=(\S+) UNIFIwifiChannelWidth=(\S+) UNIFIwifiName=(.*?) UNIFIwifiBand=(\S+) UNIFIauthMethod=(\S+) UNIFIWiFiRssi=(-?\d+) UNIFInetworkName=(\S+) UNIFInetworkSubnet=(\S+) UNIFInetworkVlan=(\S+) UNIFIutcTime=(\S+) msg=(.*)$`,
			Fields: []FieldSeed{
				{Name: "category", Label: "Category", Type: "string"},
				{Name: "unifi_host", Label: "UniFi Host", Type: "string"},
				{Name: "ap_name", Label: "AP Name", Type: "string"},
				{Name: "ap_ip", Label: "AP IP", Type: "string"},
				{Name: "ap_mac", Label: "AP MAC", Type: "string"},
				{Name: "ap_model", Label: "AP Model", Type: "string"},
				{Name: "ap_version", Label: "AP Version", Type: "string"},
				{Name: "client_alias", Label: "Client Alias", Type: "string"},
				{Name: "client_hostname", Label: "Client Hostname", Type: "string"},
				{Name: "client_ip", Label: "Client IP", Type: "string"},
				{Name: "client_mac", Label: "Client MAC", Type: "string"},
				{Name: "wifi_channel", Label: "WiFi Channel", Type: "string"},
				{Name: "wifi_channel_width", Label: "WiFi Channel Width", Type: "string"},
				{Name: "wifi_name", Label: "WiFi Name (SSID)", Type: "string"},
				{Name: "wifi_band", Label: "WiFi Band", Type: "string"},
				{Name: "auth_method", Label: "Auth Method", Type: "string"},
				{Name: "wifi_rssi", Label: "WiFi RSSI", Type: "string"},
				{Name: "network_name", Label: "Network Name", Type: "string"},
				{Name: "network_subnet", Label: "Network Subnet", Type: "string"},
				{Name: "network_vlan", Label: "Network VLAN", Type: "string"},
				{Name: "utc_time", Label: "UTC Time", Type: "string"},
				{Name: "msg", Label: "Message", Type: "string"},
			},
		},
		{
			Name:        "UniFi Network Admin Access",
			Description: "Matches UniFi Network controller audit events for admin login (signature 544)",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "|544|Network Accessed|",
			Regex:       `^(?:\d{4}-\d{2}-\d{2}T[\d:.]+Z?\s+\S+\s+(?:CEF:)?)?0\|Ubiquiti\|UniFi Network\|([^|]+)\|544\|Network Accessed\|\d+\|UNIFIcategory=(\S+) UNIFIhost=(.+?) UNIFIaccessMethod=(\S+) UNIFIadmin=(\S+) src=(\d+\.\d+\.\d+\.\d+) UNIFIutcTime=(\S+) msg=(.*)$`,
			Fields: []FieldSeed{
				{Name: "device_id", Label: "Device ID", Type: "string"},
				{Name: "category", Label: "Category", Type: "string"},
				{Name: "host", Label: "Host", Type: "string"},
				{Name: "access_method", Label: "Access Method", Type: "string"},
				{Name: "admin", Label: "Admin", Type: "string"},
				{Name: "src_ip", Label: "Source IP", Type: "string"},
				{Name: "utc_time", Label: "UTC Time", Type: "string"},
				{Name: "msg", Label: "Message", Type: "string"},
			},
		},
		{
			Name:        "UniFi OS Admin Access",
			Description: "Matches UniFi OS admin access events (signature 1000)",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "|1000|Admin Accessed UniFi OS|",
			Regex:       `^(?:\d{4}-\d{2}-\d{2}T[\d:.]+Z?\s+\S+\s+(?:CEF:)?)?0\|Ubiquiti\|UniFi OS\|([^|]+)\|1000\|Admin Accessed UniFi OS\|\d+\|UNIFIhost=(\S+) UNIFIdeviceName=(.+?) UNIFIdeviceModel=(\S+) UNIFIdeviceIp=(\d+\.\d+\.\d+\.\d+) UNIFIdeviceMac=(\S+) UNIFIdeviceVersion=(\S+) UNIFIadmin=(\S+) UNIFIaccessMethod=(\S+) msg=(.*)$`,
			Fields: []FieldSeed{
				{Name: "device_version", Label: "Device Version", Type: "string"},
				{Name: "host", Label: "Host", Type: "string"},
				{Name: "device_name", Label: "Device Name", Type: "string"},
				{Name: "device_model", Label: "Device Model", Type: "string"},
				{Name: "device_ip", Label: "Device IP", Type: "string"},
				{Name: "device_mac", Label: "Device MAC", Type: "string"},
				{Name: "device_ver", Label: "Device Version", Type: "string"},
				{Name: "admin", Label: "Admin", Type: "string"},
				{Name: "access_method", Label: "Access Method", Type: "string"},
				{Name: "msg", Label: "Message", Type: "string"},
			},
		},
		{
			Name:        "UniFi Network Generic CEF",
			Description: "Generic UniFi Network controller CEF parser for all signatures not covered by specific parsers",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "Ubiquiti|UniFi Network|",
			Regex:       `^(\d)\|([^|]+)\|([^|]+)\|([^|]+)\|(\d+)\|([^|]+)\|(\d+)\|(.+)$`,
			Fields: []FieldSeed{
				{Name: "sequence", Label: "Sequence", Type: "string"},
				{Name: "vendor", Label: "Vendor", Type: "string"},
				{Name: "product", Label: "Product", Type: "string"},
				{Name: "device_id", Label: "Device ID", Type: "string"},
				{Name: "port", Label: "Port", Type: "string"},
				{Name: "event", Label: "Event", Type: "string"},
				{Name: "severity", Label: "Severity", Type: "string"},
				{Name: "raw_kv", Label: "Raw Key-Value", Type: "string"},
			},
		},
		{
			Name:        "UniFi Network WiFi Client Disconnected",
			Description: "Matches UniFi Network controller CEF events for WiFi client disconnection (signature 401)",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "|401|WiFi Client Disconnected|",
			Regex:       `^0\|Ubiquiti\|UniFi Network\|[^|]*\|401\|WiFi Client Disconnected\|\d+\|UNIFIcategory=(.*?) UNIFIhost=(.*?) UNIFIlastConnectedToDeviceName=(.*?) UNIFIlastConnectedToDeviceIp=(\S+) UNIFIlastConnectedToDeviceMac=(\S+) UNIFIlastConnectedToDeviceModel=(\S+) UNIFIlastConnectedToDeviceVersion=(\S+) UNIFIclientAlias=(.*?) UNIFIclientHostname=(\S+) UNIFIclientIp=(\S+) UNIFIclientMac=(\S+) UNIFIwifiChannel=(\S+) UNIFIwifiChannelWidth=(\S+) UNIFIwifiName=(.*?) UNIFIwifiBand=(\S+) UNIFIwifiAirtimeUtilization=(\S+) UNIFIwifiInterference=(\S+) UNIFIlastConnectedToWiFiRssi=(-?\d+) UNIFIduration=(.*?) UNIFIusageDown=(.*?) UNIFIusageUp=(.*?) UNIFInetworkName=(\S+) UNIFInetworkSubnet=(\S+) UNIFInetworkVlan=(\S+) UNIFIutcTime=(\S+) msg=(.*)$`,
			Fields: []FieldSeed{
				{Name: "category", Label: "Category", Type: "string"},
				{Name: "unifi_host", Label: "UniFi Host", Type: "string"},
				{Name: "last_ap_name", Label: "Last AP Name", Type: "string"},
				{Name: "last_ap_ip", Label: "Last AP IP", Type: "string"},
				{Name: "last_ap_mac", Label: "Last AP MAC", Type: "string"},
				{Name: "last_ap_model", Label: "Last AP Model", Type: "string"},
				{Name: "last_ap_version", Label: "Last AP Version", Type: "string"},
				{Name: "client_alias", Label: "Client Alias", Type: "string"},
				{Name: "client_hostname", Label: "Client Hostname", Type: "string"},
				{Name: "client_ip", Label: "Client IP", Type: "string"},
				{Name: "client_mac", Label: "Client MAC", Type: "string"},
				{Name: "wifi_channel", Label: "WiFi Channel", Type: "string"},
				{Name: "wifi_channel_width", Label: "WiFi Channel Width", Type: "string"},
				{Name: "wifi_name", Label: "WiFi Name (SSID)", Type: "string"},
				{Name: "wifi_band", Label: "WiFi Band", Type: "string"},
				{Name: "wifi_airtime_utilization", Label: "WiFi Airtime Utilization", Type: "string"},
				{Name: "wifi_interference", Label: "WiFi Interference", Type: "string"},
				{Name: "last_wifi_rssi", Label: "Last WiFi RSSI", Type: "string"},
				{Name: "duration", Label: "Duration", Type: "string"},
				{Name: "usage_down", Label: "Usage Down", Type: "string"},
				{Name: "usage_up", Label: "Usage Up", Type: "string"},
				{Name: "network_name", Label: "Network Name", Type: "string"},
				{Name: "network_subnet", Label: "Network Subnet", Type: "string"},
				{Name: "network_vlan", Label: "Network VLAN", Type: "string"},
				{Name: "utc_time", Label: "UTC Time", Type: "string"},
				{Name: "msg", Label: "Message", Type: "string"},
			},
		},
	}...)
}
