package parsers

func init() {
	AllParsers = append(AllParsers, []ParserSeed{
		{
			Name:        "Ubiquiti AP Event",
			Description: "Matches Ubiquiti UniFi AP connect/disconnect/reboot events",
			DeviceType:  "ubiquiti",
			MatchType:   "hostname",
			MatchValue:  "ubnt*",
			Regex:       `AP\s+([0-9A-Fa-f:]+)\s+(\S+)\s+on\s+(\S+)`,
			Fields: []FieldSeed{
				{Name: "mac_address", Label: "MAC Address", Type: "string"},
				{Name: "event_type", Label: "Event Type", Type: "string"},
				{Name: "site", Label: "Site", Type: "string"},
			},
		},
		{
			Name:        "Ubiquiti Client Connect",
			Description: "Matches Ubiquiti client association events",
			DeviceType:  "ubiquiti",
			MatchType:   "hostname",
			MatchValue:  "ubnt*",
			Regex:       `client\s+([0-9A-Fa-f:]+)\s+(\S+)\s+on\s+(\S+)\s+channel\s+(\d+)$`,
			Fields: []FieldSeed{
				{Name: "client_mac", Label: "Client MAC", Type: "string"},
				{Name: "action", Label: "Action", Type: "string"},
				{Name: "ssid", Label: "SSID", Type: "string"},
				{Name: "channel", Label: "Channel", Type: "string"},
			},
		},
		{
			Name:        "Ubiquiti Firewall Log",
			Description: "Matches Ubiquiti EdgeRouter/Dream Machine iptables-style firewall logs",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "DESCR=",
			Regex:       `\[(\S+)\]\s+DESCR="([^"]+)"\s+IN=(\S*)\s+OUT=(\S*)\s+MAC=(\S*)\s+SRC=(\d+\.\d+\.\d+\.\d+)\s+DST=(\d+\.\d+\.\d+\.\d+)\s+.*?LEN=(\d+)\s+.*?PROTO=(\S+)(?:\s+SPT=(\d+))?(?:\s+DPT=(\d+))?`,
			Fields: []FieldSeed{
				{Name: "rule_id", Label: "Rule ID", Type: "string"},
				{Name: "description", Label: "Description", Type: "string"},
				{Name: "in_iface", Label: "In Interface", Type: "string"},
				{Name: "out_iface", Label: "Out Interface", Type: "string"},
				{Name: "mac_address", Label: "MAC Address", Type: "string"},
				{Name: "src_ip", Label: "Source IP", Type: "string"},
				{Name: "dst_ip", Label: "Dest IP", Type: "string"},
				{Name: "packet_len", Label: "Packet Length", Type: "string"},
				{Name: "proto", Label: "Protocol", Type: "string"},
				{Name: "src_port", Label: "Source Port", Type: "string"},
				{Name: "dst_port", Label: "Dest Port", Type: "string"},
			},
		},
		{
			Name:        "UniFi Network WiFi Client Connected",
			Description: "Matches UniFi Network controller CEF events for WiFi client association (signature 400)",
			DeviceType:  "ubiquiti",
			MatchType:   "message",
			MatchValue:  "|400|WiFi Client Connected|",
			Regex:       `^0\|Ubiquiti\|UniFi Network\|[^|]*\|400\|WiFi Client Connected\|\d+\|UNIFIcategory=(.*?) UNIFIhost=(.*?) UNIFIconnectedToDeviceName=(.*?) UNIFIconnectedToDeviceIp=(\S+) UNIFIconnectedToDeviceMac=(\S+) UNIFIconnectedToDeviceModel=(\S+) UNIFIconnectedToDeviceVersion=(\S+) UNIFIclientAlias=(.*?) UNIFIclientHostname=(\S+) UNIFIclientIp=(\S+) UNIFIclientMac=(\S+) UNIFIwifiChannel=(\S+) UNIFIwifiChannelWidth=(\S+) UNIFIwifiName=(.*?) UNIFIwifiBand=(\S+) UNIFIauthMethod=(\S+) UNIFIWiFiRssi=(-?\d+) UNIFInetworkName=(\S+) UNIFInetworkSubnet=(\S+) UNIFInetworkVlan=(\S+) UNIFIutcTime=(\S+) msg=(.*)$`,
			Fields: []FieldSeed{
				{Name: "category", Label: "Category", Type: "string"},
				{Name: "unifi_host", Label: "UniFi Host", Type: "string"},
				{Name: "ap_name", Label: "AP Name", Type: "string"},
				{Name: "ap_ip", Label: "AP IP", Type: "string"},
				{Name: "ap_mac", Label: "AP MAC", Type: "string"},
				{Name: "ap_model", Label: "AP Model", Type: "string"},
				{Name: "ap_version", Label: "AP Version", Type: "string"},
				{Name: "client_alias", Label: "Client Alias", Type: "string"},
				{Name: "client_hostname", Label: "Client Hostname", Type: "string"},
				{Name: "client_ip", Label: "Client IP", Type: "string"},
				{Name: "client_mac", Label: "Client MAC", Type: "string"},
				{Name: "wifi_channel", Label: "WiFi Channel", Type: "string"},
				{Name: "wifi_channel_width", Label: "WiFi Channel Width", Type: "string"},
				{Name: "wifi_name", Label: "WiFi Name (SSID)", Type: "string"},
				{Name: "wifi_band", Label: "WiFi Band", Type: "string"},
				{Name: "auth_method", Label: "Auth Method", Type: "string"},
				{Name: "wifi_rssi", Label: "WiFi RSSI", Type: "string"},
				{Name: "network_name", Label: "Network Name", Type: "string"},
				{Name: "network_subnet", Label: "Network Subnet", Type: "string"},
				{Name: "network_vlan", Label: "Network VLAN", Type: "string"},
				{Name: "utc_time", Label: "UTC Time", Type: "string"},
				{Name: "msg", Label: "Message", Type: "string"},
			},
		},
	}...)
}
