package model

import "time"

// CloudBridgeState is this installation's identity in its operator's
// Logmara Cloud account - see backend/cloudbridge's package doc comment.
// Written exactly once, by EnrollAgent's response (see
// cloudbridge.enroll) - nothing in this codebase ever updates an existing
// row, only inserts the first one. InstanceID is generated by the cloud
// side at enrollment time, not chosen locally - unique and immutable from
// this installation's point of view.
type CloudBridgeState struct {
	ID         int64     `json:"id"`
	InstanceID string    `json:"instance_id"`
	BrokerHost string    `json:"broker_host"`
	CACert     string    `json:"-"`
	ClientCert string    `json:"-"`
	ClientKey  string    `json:"-"`
	EnrolledAt time.Time `json:"enrolled_at"`
}
